/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncas_2_0_1[] = {
	  0X102F65F0
	, 0X102F67E4
	, 0X102F6920
	, 0X102F5EDC
	, 0X102F40BC
	, 0X102FC8D0
	, 0X102F6DF8
	, 0X102F29D0
};
