/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncas_3_0_1[] = {
	  0X103762C0
	, 0X10376464
	, 0X10376658
	, 0X10375B34
	, 0X103731C8
	, 0X1037E2F8
	, 0X10376C64
	, 0X10370B98
};
