/****************************************************************************
 * Produces the patches to restore the OS variables to their original state
 * required to hot-reboot the OS.
 * 
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is Ndless code.
 *
 * The Initial Developer of the Original Code is Excale.
 * Portions created by the Initial Developer are Copyright (C) 2013
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s): Olivier ARMAND <olivier.calc@gmail.com>
 ****************************************************************************/

#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#include <stdlib.h>

#define BASE (0x10000000)

int main(int argc, char* argv[]) {
	if(argc != 5) {
		puts("Usage: MakeHotRebootPtch <0xbase> <in_before_boot.bin> <in_after_boot.bin> <out_patches.h>\n"
		     "Input files can be either OS or internal ram images.");
		return 1;
	}
	
	char *base_parse_terminated_at;
	unsigned long base = strtoul(argv[1], &base_parse_terminated_at, 16);
	if (*base_parse_terminated_at != '\0') {
		puts("Base is not an hex number\n");
		return 1;
	}

	FILE *input_before = fopen(argv[2], "rb");
	if (!input_before) {
		printf("Open #1 failed.\n");
		return 1;
	}
	FILE *input_after = fopen(argv[3], "rb");
	if (!input_after) {
		printf("Open #2 failed.\n");
		return 1;
	}
	FILE *output = fopen(argv[4], "wt");
	if(!output)	{
		printf("Open #3 failed.\n");
		return 1;
	}
	
	uint32_t word_1 = 0x0, word_2 = 0x0;
    uint32_t startaddr = 0x0, length = 0x0;
    uint32_t currtaddr = base-0x4;
    uint32_t patchword = 0;
	fputs("/* This file is generated by MakeHotRebootPtch, do not edit manually */\n", output);
	while (fread(&word_1, 4, 1, input_before) && fread(&word_2, 4, 1, input_after)) {
        if ( (length > 0) & ((word_1 == word_2) || (patchword != 0x0) || ((word_1 != word_2) && (word_1 != 0x0))) )
        {
            if (length == 1) {
                if (patchword == 0x0) {
                    fprintf(output, "PATCH_CLRW(0x%08"PRIX32");\n", currtaddr);
                }
                else  {
                    fprintf(output, "PATCH_WW(0x%08"PRIX32", 0x%08"PRIX32");\n", currtaddr, patchword);
                }
            }
            else  {
                fprintf(output, "PATCH_CLRZ(0x%08"PRIX32", 0x%08"PRIX32");\n", startaddr, currtaddr);
            }
        }
        currtaddr += 4;
        if (word_1 == word_2) {
            length = 0;
        }
        else if ((word_1 == 0x0) && (length != 0) && (patchword == 0x0)) {
            length++;
        }
        else {
            startaddr = currtaddr;
            patchword = word_1;
            length = 1;
        }
        
	}
	
	fclose(input_before);
	fclose(input_after);
	fclose(output);
	return 0;
}
