/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cascmc_3_1_0[] = { //CM-C CAS 3.1
	  0x0  //   0X10378070
	, 0x0  // , 0X10378214
	, 0x0  // , 0X103778E4
	, 0x0  // , 0X10378A14
	, 0x0  // , 0X10372948
	, 0x0  // , 0X103800A8
	, 0x0  // , 0X10379C8C
};
