/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cascmc_3_1_0[] = {
	  0X1036143C
	, 0X103615E0
	, 0X10360CB0
	, 0X10361DE0
	, 0X1035BD14
	, 0X10369400
	, 0X10363058
};
