/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cas_2_0_1[] = {
	  0X102F6EC0
	, 0X102F70B4
	, 0X102F71F0
	, 0X102F67AC
	, 0X102F498C
	, 0X102FD1A0
	, 0X102F76C8
	, 0X102F32A0
};
