/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncas_3_1_0[] = {
	  0X1037A020
	, 0X1037A1C4
	, 0X10379894
	, 0X1037A9C4
	, 0X103748F8
	, 0X10382058
	, 0X1037BC3C
};
