/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cas_3_1_0[] = {
	  0X1037A750
	, 0X1037A8F4
	, 0X10379FC4
	, 0X1037B0F4
	, 0X10375028
	, 0X10382788
	, 0X1037C36C
};
