/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncas_1_7[] = {
	  0X102A4CBC
	, 0X102A4EB0
	, 0X102A4FEC
	, 0X102A46B4
	, 0X102A280C
	, 0X102AA2CC
	, 0X102A54C4
	, 0X102A11C8
};
