#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define RESOURCE_FILE_BYTES_SIZE			5192
#define FLASH_PAGE_BYTES_SIZE					512

void printUsage() {
	puts(
		"Usage: FlashEdit <infile.tns> <flash_rom.bin> <resource_offset>\n"
		"<infile.tns> contains a loader generated by LoaderWrapper\n"
		"<flash_rom.bin> emulator rom image\n"
		"<resource_offset> offset of the resource file 'phoenix/syst/locales/en/strings' in the rom image\n\n"
		"Resource offsets:\n"
		"0x611D60 = CAS 1.1.9170"
	); 	
}

void printErrorAndExit(const char* msg, int code) {
	printf("Error: %s\n", msg);
	exit(code);
}

int getFileSize(FILE *f) {
	int pos;
	int end;

	pos = ftell(f);
	fseek (f, 0, SEEK_END);
	end = ftell(f);
	fseek (f, pos, SEEK_SET);

	return end;
}

void edit(FILE* fResource, FILE* fFlash, unsigned long resource_offset) {
	char* flash_page = (char*)malloc(FLASH_PAGE_BYTES_SIZE);
	int n;
		
	fseek(fFlash, resource_offset, SEEK_SET);
	while (!feof(fResource)) {
		n = fread(flash_page, 1, FLASH_PAGE_BYTES_SIZE, fResource);
		fwrite(flash_page, 1, n, fFlash);
		fseek(fFlash, 16, SEEK_CUR);
	}
	
	free(flash_page);
}

int main(int argc, char* argv[]) {
	FILE* fileResource, *fileFlash;
	int fileResourceSize;
	unsigned long resource_offset;
	
	if (argc != 4) {
		printUsage();
		return -1;	
	}
	
	resource_offset = strtoul(argv[3], 0, 16);
	
	fileResource = fopen(argv[1], "rb");
	if (fileResource == NULL) {
		printErrorAndExit("Could not open <infile.tns>.", 1);	
	}
	
	fileResourceSize = getFileSize(fileResource);
	if (fileResourceSize != RESOURCE_FILE_BYTES_SIZE) {
		printf("Error: <infile.tns> size must be of %d bytes\n", RESOURCE_FILE_BYTES_SIZE);
		fclose(fileResource);
		exit(3);
	}
	
	fileFlash = fopen(argv[2], "r+b");
	if (fileFlash == NULL) {
		fclose(fileResource);
		printErrorAndExit("Could not open <flash_rom.bin>.", 2);	
	}
	
	edit(fileResource, fileFlash, resource_offset);
	
	fclose(fileResource);
	fclose(fileFlash);
	
	printf("File '%s' successfully modified !\n", argv[2]);
	
	return EXIT_SUCCESS;	
}
