CC=gcc
CFLAGS = -W -Wall
SCRIPTS=install-ndless-nspire_emu.bat
vpath %.exe ../../bin

all: init FlashEdit.exe scripts

init:
	@mkdir -p ../../bin

FlashEdit.exe: FlashEdit.c
	$(CC) $(CFLAGS) $< -o ../../bin/FlashEdit.exe

scripts:
	@cp $(SCRIPTS) ../../bin

clean:
	@cd ../../bin && rm -rf FlashEdit.exe $(SCRIPTS)