CC=gcc
CFLAGS = -W -Wall
vpath ../../bin

all: init LoaderWrapper

init:
	@mkdir -p ../../bin

LoaderWrapper: LoaderWrapper.c
	$(CC) $(CFLAGS) $< -o ../../bin/LoaderWrapper
	
clean:
	@rm -rf ../../bin/LoaderWrapper