CC=gcc
CFLAGS = -W -Wall
vpath %.exe ../../bin

all: init LoaderWrapper.exe

init:
	@mkdir -p ../../bin

LoaderWrapper.exe: LoaderWrapper.c
	$(CC) $(CFLAGS) $< -o ../../bin/LoaderWrapper.exe
	
clean:
	@rm -rf ../../bin/LoaderWrapper.exe