/* Each entry matches a symbol in syscalls.h.
 * This file is generated by mksyscalls.sh from the IDC file, please DO NOT EDIT MANUALLY. */
unsigned syscalls_light_ncascx_3_6_0[] = {
	  0X103FC858
	, 0X103FC9FC
	, 0X103FC0CC
	, 0X103FD1FC
	, 0X103F6DF0
	, 0X10404950
	, 0X103FE474
	, 0X103FE2B8
};
