/* Each entry matches a symbol in syscalls.h.
 * This file is generated by mksyscalls.sh from the IDC file, please DO NOT EDIT MANUALLY. */
unsigned syscalls_light_cas_3_6_0[] = {
	  0X103FF414
	, 0X103FF5B8
	, 0X103FEC88
	, 0X103FFDB8
	, 0X103F99AC
	, 0X1040750C
	, 0X10401030
	, 0X10400E74
};
