/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cascx_3_6_0[] = {
	  0X103FD2C8
	, 0X103FD46C
	, 0X103FCB3C
	, 0X103FDC6C
	, 0X103F7860
	, 0X104053C0
	, 0X103FEEE4
	, 0X103FED28
};
