/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cmc_3_1_0[] = {
	  0X10360CAC
	, 0X10360E50
	, 0X10360520
	, 0X10361650
	, 0X1035B584
	, 0X10368C70
	, 0X103628C8
};
