/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncascx_3_1_0[] = {
	  0X103778E0
	, 0X10377A84
	, 0X10377154
	, 0X10378284
	, 0X103721B8
	, 0X1037F918
	, 0X103794FC
};
