/* Each entry matches a symbol in syscalls.h.
 * This file is generated by mksyscalls.sh from the IDC file, please DO NOT EDIT MANUALLY. */
unsigned syscalls_light_ncas_3_6_0[] = {
	  0X103FE9D4
	, 0X103FEB78
	, 0X103FE248
	, 0X103FF378
	, 0X103F8F6C
	, 0X10406ACC
	, 0X104005F0
	, 0X10400434
};
