/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cascx_3_1_0[] = {
	  0X10378070
	, 0X10378214
	, 0X103778E4
	, 0X10378A14
	, 0X10372948
	, 0X103800A8
	, 0X10379C8C
};
