/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cas_3_0_1[] = {
	  0X103769E0
	, 0X10376B84
	, 0X10376254
	, 0X10377384
	, 0X103712B8
	, 0X1037EA18
};
