/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncas_2_1_0[] = {
	  0X102F75C0
	, 0X102F77B4
	, 0X102F78F0
	, 0X102F6EAC
	, 0X102F508C
	, 0X102FDAE0
	, 0X102F7DC8
	, 0X102F37D0
};
