/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncascx_3_1_0[] = {
	  0X10373BA0
	, 0X10373D44
	, 0X10373414
	, 0X10374544
	, 0X1036E478
	, 0X1037BBD8
};
