/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cascx_3_0_2[] = {
	  0X10374790
	, 0X10374934
	, 0X10374004
	, 0X10375134
	, 0X1036F068
	, 0X1037C7C8
};
