/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cas_3_0_2[] = {
	  0X10376E70
	, 0X10377014
	, 0X103766E4
	, 0X10377814
	, 0X10371748
	, 0X1037EEA8
};
