/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncas_3_0_2[] = {
	  0X10376750
	, 0X103768F4
	, 0X10375FC4
	, 0X103770F4
	, 0X10371028
	, 0X1037E788
};
