/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cascx_3_0_1[] = {
	  0X103742F0
	, 0X10374494
	, 0X10373B64
	, 0X10374C94
	, 0X1036EBC8
	, 0X1037C328
};
