/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_ncascx_3_0_2[] = {
	  0X10374040
	, 0X103741E4
	, 0X103738B4
	, 0X103749E4
	, 0X1036E918
	, 0X1037C078
};
