/* Each entry matches a symbol in syscalls.h. This file is generated by mksyscalls.sh. */
unsigned syscalls_light_cas_2_1_0[] = {
	  0X102F7E90
	, 0X102F8084
	, 0X102F81C0
	, 0X102F777C
	, 0X102F595C
	, 0X102FE3B0
	, 0X102F8698
	, 0X102F40A0
};
